spring:
  common-web:
    messages:
      basename: classpath:i18n/messages
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://134.175.164.205:3306/dto_example
    platform: mysql
