email:
  sender:
    use-ssl: true
    protocal: smtp
    auth:
      username: xxxx@163.com
      password: XXXXX
  receive:
    use-ssl: false
    protocal: imap
    auth:
      username: 1253950375@qq.com
      password: cftqmaqtgjrxjdga
