email:
  sender:
    use-ssl: true
    protocal: smtp
    auth:
      username: yumiaoxia132@163.com
      password: yuzi940710
  receive:
    user-ssl: true
    protocal: imap
    auth:
      username: yumiaoxia132@163.com
      password: yuzi940710