email:
  sender:
    use-ssl: true
    protocal: smtp
    auth:
      username: yumiaoxia132@163.com
      password: yuzi940710
  receive:
    use-ssl: false
    protocal: imap
    auth:
      #      username: yumiaoxia132@163.com
      #      password: yuzi940710
      username: 1253950375@qq.com
      password: cftqmaqtgjrxjdga